pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pull the latest code from GitHub repository
                git 'https://github.com/Artistic18/weather-app.git'
            }
        }

        stage('Print') {
            steps {
                // Print the contents of the repository to verify the checkout
                sh 'ls -al'
            }
        }
    }
}